### ISSUE TITLE
[Feature]: 교수진 소개 페이지 Route handlers 및 토큰 적용

### ISSUE THREAD

**Issue by SunwooJaeho** [kgu-developers/aics-client#28]
### Describe

교수진 소개 페이지에 Route Handlers와 토큰을 적용합니다.

### Tasks

- [x] Route Handlers 적용
- [x] 토큰 적용

**Comment by gwansikk** [comment]
msw는 모킹을 도와주는 라이브러리 명칭입니다(지원하지 않는 이유로 우리 프로젝트에는 사용하지 않아요). 모킹 혹은 Route Handlers라고 표현하는 것이 명확해요

**Comment by SunwooJaeho** [comment]
> msw는 모킹을 도와주는 라이브러리 명칭입니다(지원하지 않는 이유로 우리 프로젝트에는 사용하지 않아요). 모킹 혹은 Route Handlers라고 표현하는 것이 명확해요

수정 완료했어요!
